#!/bin/bash

set -e

# Test
if [ "$1" = "test" ]; then
    # Configure Git
    git config --global --add safe.directory '*'

    # Generate dependencies
    make depend

    # Run tests
    make test

    exit 0
fi

# Build
if [ "$1" = "build" ]; then
    # Configure Git
    git config --global --add safe.directory '*'

    # Add external dependencies
    apt update
    apt install -y zip

    # Generate dependencies
    make depend

    # Run tests
    make

    exit 0
fi
